version: '2'

services:
  container_web:    
    image: nginx    
    ports:
        - "80:80"
        - "443:443"        
    volumes:        
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw        
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
        - ./nginx/400.html:/usr/share/nginx/html/404.html:ro
        - ./nginx/50x.html:/usr/share/nginx/html/50x.html:ro
        - ./nginx/log:/var/log/nginx:rw
        - ./dist/releases:/usr/share/nginx/html:rw        
    environment:
        - NGINX_HOST=web
        - NGINX_PORT=80
